/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Enum;

/**
 *
 * @author tux
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainFrame() {
//        super("Titulo de ventanaaaaaaaaaaaaaaa");
        initComponents();
    }

    public javax.swing.JTable getjTable() {
        return jTable1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jCheckBoxString = new javax.swing.JCheckBox();
        jCheckBoxInteger = new javax.swing.JCheckBox();
        jCheckBoxEnum = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("New property"));

        jButton1.setText("New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBoxString.setSelected(true);
        jCheckBoxString.setText("String");
        jCheckBoxString.setEnabled(false);

        jCheckBoxInteger.setText("Integer");
        jCheckBoxInteger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIntegerActionPerformed(evt);
            }
        });

        jCheckBoxEnum.setText("Enum");
        jCheckBoxEnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEnumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxString)
                    .addComponent(jCheckBoxInteger)
                    .addComponent(jCheckBoxEnum))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxString)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxInteger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBoxEnum))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (!this.jCheckBoxInteger.isSelected() && !this.jCheckBoxEnum.isSelected()) {
            CUStringJFrame f = new CUStringJFrame(this.jTable1.getModel(), 'c');
            f.setTitle("Create String");
            f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            f.pack();
            f.setVisible(true);
        } else if (this.jCheckBoxInteger.isSelected() && !this.jCheckBoxEnum.isSelected()) {
            CUIntegerJFrame f = new CUIntegerJFrame(this.jTable1.getModel(),'c');
            f.setTitle("Create Integer");
            f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            f.pack();
            f.setVisible(true);
        } else if (!this.jCheckBoxInteger.isSelected() && this.jCheckBoxEnum.isSelected()) {
            CUEnumJFrame f = new CUEnumJFrame(this.jTable1.getModel(), 'c');
            f.setTitle("Create Enum");
            f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            f.pack();
            f.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int rowSelected = this.jTable1.getSelectedRow();
        if (rowSelected != -1) {
            DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
            Object item = model.getValueAt(rowSelected, 0);
            if (item instanceof objetos.String) {
                CUStringJFrame f = new CUStringJFrame(this.jTable1.getModel(), 'e', this.jTable1.getSelectedRow());
                f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                f.setTitle("Edit String");
                f.pack();
                f.setVisible(true);
            } else if (item instanceof objetos.Integer) {
                CUIntegerJFrame f = new CUIntegerJFrame(this.jTable1.getModel(),'e', this.jTable1.getSelectedRow());
                f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                f.setTitle("Edit Integer");
                f.pack();
                f.setVisible(true);
            } else if (item instanceof Enum) {
                CUEnumJFrame f = new CUEnumJFrame(this.jTable1.getModel(), 'e', this.jTable1.getSelectedRow());
                f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                f.setTitle("Edit Enum");
                f.pack();
                f.setVisible(true);
            }

//            model.removeRow(rowSelected);
        } else {
            JOptionPane optionPane = new JOptionPane("You must select an item to edit.",
                    JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog(this, "!Error");
            dialog.setVisible(true);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
//        model.get
        int rowSelected = this.jTable1.getSelectedRow();
        if (rowSelected != -1) {
            DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
            model.removeRow(rowSelected);
        } else {
            JOptionPane optionPane = new JOptionPane("You must select an item to delete.",
                    JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog(this, "!Error");
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBoxIntegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIntegerActionPerformed
        this.jCheckBoxEnum.setSelected(false);
    }//GEN-LAST:event_jCheckBoxIntegerActionPerformed

    private void jCheckBoxEnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEnumActionPerformed
        this.jCheckBoxInteger.setSelected(false);
    }//GEN-LAST:event_jCheckBoxEnumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                JFrame f = new MainFrame("Titulo de ventana");

//                MainFrame f = new MainFrame();
//                f.setSize(400, 300);
//                f.setTitle("Titulo de ventana");
//                f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//                
//
//                Object rowData[][] = {{"Row1-Column1", "Row1-Column2", "Row1-Column3"},
//                {"Row2-Column1", "Row2-Column2", "Row2-Column3"}};
//                Object columnNames[] = {"Column One", "Column Two", "Column Three"};
//
//                TableModel model = new DefaultTableModel(rowData, columnNames);
//                f.jTable1.setModel(model);
//                
//                
//                f.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBoxEnum;
    private javax.swing.JCheckBox jCheckBoxInteger;
    private javax.swing.JCheckBox jCheckBoxString;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
